# Please put your runtime parameters: 
# name, and a space, followed by values 

# sim variables
sim_name 'shu'
sim_fixDt .false.
sim_cfl 0.8
sim_tmax 1.8
sim_nstep 1000000
sim_nlim  .false.
sim_outputIntervalTime 0.1
sim_riemann 'hllc'
sim_limiter 'mc'
sim_charLimiting .true.
sim_WENO 'Z'               #'5' or 'Z'
sim_mval 2		   #ROC power for betas'
sim_WENeps 1.e-36
sim_quad 'exact'
sim_sigma 0.
sim_sigdel 12.
sim_intFlux .true.

# grid variables
gr_ngc 8
gr_xbeg 0.
gr_xend 9.

# problem specific physical IC
sim_icType 'shu'
sim_shockLoc 0.5
sim_densL 1.0
sim_velxL 0.0 #-2. #0.
sim_presL 1.0 #0.4 #1.
sim_densR 0.125 #0.125
sim_velxR 0.0 #0.
sim_presR 0.1 #0.1
sim_gamma 1.4
sim_smallPres 1.e-12

# BC type
sim_bcType 'user'

# IO frequency
sim_ioTfreq 10. #real
sim_ioNfreq -1    #positive integer; zero or negative if not used

sim_dt 0.0125
sim_order 10
sim_RK .true.
sim_Torder 3
gp_radius 2
gp_el 0.
      
